# Generated by Django 5.0.6 on 2024-10-08 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leaders', models.ManyToManyField(related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participated_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
