@echo off
echo Running flake8...
flake8 --exclude=venv,.venv,env,Lib,site-packages .
echo Running pylint...
pylint --load-plugins pylint_django --ignore=venv,.venv,env,Lib,site-packages your_project_name apps
echo Running black check...
black --check --exclude="/(venv|.venv|env|Lib|site-packages)/" .
echo Running isort check...
isort --check-only --skip=venv --skip=.venv --skip=env --skip=Lib --skip=site-packages .